spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.44.130
    port: 5672
    username: admin
    password: admin
  
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://eureka1:2001/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      
---
spring:
  profiles: item1

server:
  port: 8001
  
---
spring:
  profiles: item2
server:
  port: 8002