sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
    
eureka:
  instance:
    ### 心跳间隔时间,默认30秒
    lease-renewal-interval-in-seconds: 30
  client:
    ### 拉取注册信息时间,默认30秒
    registry-fetch-interval-seconds:  30
    service-url:
       ### 默认位置,可以修改为具体地理位置,比如beijing,shangHai,shenZhen 等,
       #表示eureka服务器的部署位置
      defaultZone: http://eureka1:2001/eureka
  
---
spring.profiles: user1

server:
  port: 8101

---
spring.profiles: user2

server:
  port: 8102
