sp:
  user-service:
    users: "[{\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.44.130
    port: 5672
    username: admin
    password: admin
    
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    registry-fetch-interval-seconds:  30
    service-url:
      defaultZone: http://eureka1:2001/eureka
      
  
---
spring.profiles: user1

server:
  port: 8101

---
spring.profiles: user2

server:
  port: 8102
